<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br><br><br>

# Listed Volatility and Variance Derivatives

**Wiley Finance (2017)**

Dr. Yves J. Hilpisch | The Python Quants GmbH

http://tpq.io | [@dyjh](http://twitter.com/dyjh) | http://books.tpq.io

<img src="https://hilpisch.com/images/lvvd_cover.png" alt="Listed Volatility and Variance Derivatives" width="30%" align="left" border="0">

# Model-Free Replication of Variance

## Simple Spanning with Options

In [1]:
import numpy as np

In [2]:
S = np.array((20, 5))
B = np.array((11, 11))

In [3]:
S0 = 10
B0 = 10

In [4]:
M = np.array((S, B)).T
M

array([[20, 11],
       [ 5, 11]])

In [5]:
M0 = np.array((S0, B0))

In [6]:
K = 14

In [7]:
C = np.maximum(S - K, 0)
C

array([6, 0])

In [8]:
P = np.maximum(K - S, 0)
P

array([0, 9])

In [9]:
phi_C = np.linalg.solve(M, C)
phi_C

array([ 0.4       , -0.18181818])

In [10]:
phi_P = np.linalg.solve(M, P)
phi_P

array([-0.6       ,  1.09090909])

In [11]:
C0 = np.dot(M0, phi_C)
C0

np.float64(2.1818181818181817)

In [12]:
P0 = np.dot(M0, phi_P)
P0

np.float64(4.909090909090908)

In [13]:
M_ = np.array((C, P)).T
M_

array([[6, 0],
       [0, 9]])

In [14]:
M0_ = np.array((C0, P0))
M0_

array([2.18181818, 4.90909091])

In [15]:
s1 = np.array((1, 0))
s2 = np.array((0, 1))

In [16]:
phi_s1 = np.linalg.solve(M_, s1)
phi_s1

array([0.16666667, 0.        ])

In [17]:
phi_s2 = np.linalg.solve(M_, s2)
phi_s2

array([0.        , 0.11111111])

In [18]:
p1 = np.dot(M0_, phi_s1)
p1

np.float64(0.3636363636363636)

In [19]:
p2 = np.dot(M0_, phi_s2)
p2

np.float64(0.5454545454545453)

In [20]:
M0_s = np.array((p1, p2))

In [21]:
g = np.array((13, 3))

In [22]:
g0 = np.dot(M0_s, g)
g0

np.float64(6.363636363636362)

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:team@tpq.io">team@tpq.io</a>